name: SAST Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install bandit
        run: pip install bandit

      - name: run it
        run: bandit -r webapp/ -f json -o bandit_results.json
        continue-on-error: true
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install semgrep
        run: pip install semgrep

      - name: run semgrep
        run: semgrep scan --config="p/owasp-top-ten" --config="custom-rules.yaml" --json -o sast_scan_results.json --error .

      - name: upload semgrep artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-scan-results
          path: sast_scan_results.json
  sonarcloud:
    needs: [bandit, semgrep]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: sonarcloud scan
        uses: sonarsource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}