name: SAST Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: set up python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'

      - name: install bandit
        run: pip install pbr bandit

      - name: run bandit (fail on HIGH severity)
        run: bandit -r webapp/ -f json -o bandit_results.json -ll

      - name: upload bandit artifact
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bandit-results
          path: bandit_results.json
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: set up python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'

      - name: install semgrep
        run: pip install semgrep==1.72.0

      - name: run semgrep
        run: semgrep scan --config="p/owasp-top-ten" --config="custom-rules.yaml" --json -o sast_scan_results.json --error .

      - name: upload semgrep artifact
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sast-scan-results
          path: sast_scan_results.json
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: set up python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'

      - name: dependency vulnerability scan
        run: pip install pip-audit==2.7.3 && pip-audit -r webapp/requirements.txt -f json -o sca_results.json

      - name: upload sca artifact
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sca-results
          path: sca_results.json
  sonarcloud:
    needs: [bandit, semgrep, sca]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: sonarcloud scan
        uses: sonarsource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}